### ISSUE TITLE
Position of the opam-version line

### ISSUE THREAD

**Issue by pbaudin** [tarides/dune-release#441]
Following this discussion at [opam-repository](https://github.com/ocaml/opam-repository/pull/21108#discussion_r843170008) the line containing the field `opam-version:` should be the first line of the `.opam` file that `dune-release` pushes to the `opam-repository`.

But, when the `.opam` file is generated from a `.opam.template` file by `dune`, it prepends some generated lines before those of the template (even if the `opam-version` field is specified in the first line of the template). So, the `opam` file pushed by `dune-release` to  `opam-repository` does not meet the _opam_ constraints..

It would be nice if `dune-relase` can check the position of the opam-version line before publishing the package.
Of course, it would be better if that line could be reordered by `dune-release` when publishing the `opam` file to  `opam-repository`.

I noticed that `dune-project` file have the same kind of constraint: `dune` rejects `dune-project` file starting by some comment lines.

**Comment by pbaudin** [comment]
I can't say from https://github.com/ocaml/opam-repository/pull/21108#discussion_r843170008 if that is mandatory or just a recommend good practice by the opam team.

**Comment by Leonidas-from-XIV** [comment]
I believe https://github.com/pbaudin/fontforge-of-ocaml/pull/1 is a better fix, since there is no reason I can think of to have `opam-version` in a template file.

I'm closing this, as the `.opam` file is generated by dune and if the case of `opam-version` in the template would have to be handled this would need to happen on the dune side.
