### ISSUE TITLE
Skip changelog's unreleased section if present

### ISSUE THREAD

**Issue by mbarbin** [tarides/dune-release#481]
### current changelog workflow

My understanding for the typical workflow of a release cycle involves:

1. creating a commit <prepare-release> where the changelog's section `unreleased` is replaced by an actual version number.
2. run `dune-release tag` ; `dune-release`
3. create a new commit <prepare-new-cycle> where a new empty section `unreleased` is added back to the changelog

### a possible twist (currently doesn't work)

Before I knew about `dune-release`, I was under the impression that you could do 1 and 3 as part of the same commit, just prior to the release (thus avoiding to having to remember to do 3 after the release). That is, when you mark the `unreleased` section with an actual number, at the same time you can add the new empty section on top.

This however doesn't work well with `dune-release`, because if you do 1 & 3 at once, by the time you run `dune-release tag` it believes `unreleased` is your version number (this is the heuristic that extracts that information from the changelog). And even if you do your tagging manually, by the time you run `dune-release publish distrib` it will still extract the wrong distrib changelog message (extracting the empty section rather than the section about that version).

### Proposal

Do you think it would be OK to slightly change dune-release's changelog heuristic to simply skip over the `unreleased` section of the changelog (and perhaps fails if it not empty) ? That would allow removing the need for the extra commit at the end.

Currently you can still avoid 3 and let the first subsequent post-release PR add back the unreleased section if it's missing. But I wonder if this is not too much to ask to the submitter of a PR, especially if they're not familiar with the changelog expected format (although this can be retrieved from the history).

Thanks!

**Comment by Leonidas-from-XIV** [comment]
I see where you're coming from (because I often times forget to re-add the unreleased section). The problem I see is that if you skip over unreleased sections, then either 

1. the changelog in the released tarball would differ from the git repo, thus there isn't really a correspondence between a particular commit and a tarball. Which isn't terrible but it is not nice
2. the tarball would start with an unreleased section so every reader of the changelog (human or machine) would need to handle the section specially and skip it

Neither of those consequences seems particularly nice.

Another option I could imagine would be to automatically (opt-in) add a section to the change log after `dune-release distrib`, then of course you still have to commit and push but at least the change is already in the work tree.

**Comment by mbarbin** [comment]
Thanks for your response ! I must say I did not think about the tarball much, and thus I appreciate your insight.

So far, I was under the impression that users would not interact much with the actual context of the tarball, as it's probably kept somewhere internal inside ~/.opam and thus did not think much about it. Could you give me some examples of workflow involving reading the changelog from the tarball ? (does opam do for example?)

That being said:

> 1. the changelog in the released tarball would differ from the git repo

I didn't mean this  to be a consequence of it, rather only change how `dune-release` extracts information from it. It would be kept equal to its state at the commit that has the tag (with the leading empty unreleased section).

> there isn't really a correspondence between a particular commit and a tarball. Which isn't terrible but it is not nice

I think it is already the case anyways, since things like `dune subst` run and apply some interpolation. But agreed that keeping the differences to a minimal is desirable.

> the tarball would start with an unreleased section so every reader of the changelog (human or machine) would need to handle the section specially and skip it

Perhaps many changelogs start directly with the section of the released version as their first paragraph ? I was trying to use https://keepachangelog.com/en/1.1.0/ which has a general leading section anyways, thus not thinking having a bit more lines in addition would be a problem.

I've noticed `dune-release publish distrib` extracts the section to add it as GitHub release message. As a workaround I've provided it with the option `-m "Published using dune-release"`, thus enabling me to keep my empty unreleased section. As a consequence, a distribution published that way doesn't have the release notes as metadata on GitHub, but I don't know if that place is discoverable by users.

Do you know the main places users consume the changelog notes from?

**Comment by Leonidas-from-XIV** [comment]
The tarball is not only in a hidden folder but also uploaded to your "releases" page so to me it feels like the primary source people are going to interact with your project. These days people are probably more inclined to check your project sources on Github, yet I do think that if I download a tarball of `project-1.0.tar.gz` and the changelog has an `unreleased` section, I would be somewhat wondering whether they messed up their release process.

I don't know who consumes changelogs, because the nature of this is a bit distributed but I could e.g. imagine that the OCaml Newsletter or CWN scans changelogs of packages released on OPAM. To be fair, the changelog formats are a bit of a mess, so there is only so much you can automate (even `dune-release` didn't support the keepachangelog format).

The other thing is, that not all projects deal with `unreleased` sections the same way. Some don't have sections (Menhir), some write the changelog only when releasing and e.g. dune/opam don't write them into the changelog right away, but rather keep the unreleased changes somewhere else and compile them together by the release manager). So there are certainly a lot of workflows and I am not sure one is more valid than others.

**Comment by mbarbin** [comment]
I browsed a bit the packages I happen to currently have inside `.opam/5.1.0/.opam-switch/sources`, and now I realize it's indeed nice to see pretty much all changelogs start directly with the section relevant to the package version.

I think I'll drop the leading section of the keepachangelog format and amend my workflow. Having the support of `dune-release` for the GitHub releases pages seems to be too good to pass.

Thus I plan on closing this issue and will do some more experimenting.

Thank you!
